### ISSUE TITLE
Error while inserting UTXO: Network type mismatch

### ISSUE THREAD

**Issue by HonzaR** [Electric-Coin-Company/zcash-android-wallet-sdk#1657]
#### If so, please list the steps to reproduce below:
1. 
2. 
3. 

### Actual behavior + errors
```
                 java.lang.RuntimeException: Error while inserting UTXO: Data DB is corrupted: Network type mismatch: account UIVK is for mainnet but a testnet address was requested.
                 	at cash.z.ecc.android.sdk.internal.jni.RustBackend.putUtxo(Native Method)
                 	at cash.z.ecc.android.sdk.internal.jni.RustBackend.access$putUtxo(RustBackend.kt:27)
                 	at cash.z.ecc.android.sdk.internal.jni.RustBackend$Companion.putUtxo(Unknown Source:0)
                 	at cash.z.ecc.android.sdk.internal.jni.RustBackend$Companion.access$putUtxo(RustBackend.kt:499)
                 	at cash.z.ecc.android.sdk.internal.jni.RustBackend$putUtxo$2.invokeSuspend(RustBackend.kt:463)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                 	at java.lang.Thread.run(Thread.java:1012)
```

- App Version: 
- Android Version:
- Device: (if applies)

**Comment by HonzaR** [comment]
This is related to #1538, as we now deliver any BE `putUtxo` API error to clients. The Rust BE now replies with such an error.

**Comment by daira** [comment]
In a pairing @str4d mentioned that he had seen a similar problem in the DerivationTool code, and that one of the reasons he had put the `network_id` arguments last is so that any mismatch in API signatures would cause a network mismatch. At that point I happened to look at the list of recent issues including https://github.com/Electric-Coin-Company/zcash-android-wallet-sdk/issues/1684 , which might very well be the cause of this bug. Notice that at https://github.com/Electric-Coin-Company/zcash-android-wallet-sdk/blob/a3ac1d3dda29412977f82e6e3d67383890bd1556/backend-lib/src/main/rust/lib.rs#L1614 , `height` is declared as `jint` in Rust, but at https://github.com/Electric-Coin-Company/zcash-android-wallet-sdk/blob/a3ac1d3dda29412977f82e6e3d67383890bd1556/backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/jni/RustBackend.kt#L852 it is declared as `Long` in Kotlin. (`Int` should correspond to `jint`, and `Long` to `jlong`.) This would cause undefined behaviour and depending on the ABI, an incorrect value for the `network_id` argument.

**Comment by str4d** [comment]
The root cause of the bug is that the Kotlin side was changed from `height: Int` to `height: Long` in #594 without the Rust side also being updated. Most other JNI methods did have both sides updated correctly; this is just one that happened to be missed.

**Comment by HonzaR** [comment]
Closing as done.
