### ISSUE TITLE
Error while requesting the current address from the Rust layer over JNI

### ISSUE THREAD

**Issue by HonzaR** [Electric-Coin-Company/zcash-android-wallet-sdk#1658]
#### If so, please list the steps to reproduce below:
1. 
2. 
3. 

### Actual behavior + errors
```
FATAL EXCEPTION: DefaultDispatcher-worker-1 (Ask Gemini)
                 Process: co.electriccoin.zcash.debug, PID: 28426
                 cash.z.ecc.android.sdk.exception.RustLayerException$GetCurrentAddressException: Error while requesting the current address from the Rust layer over JNI. This might mean that the SDK is not yet correctly set up.
                 	at cash.z.ecc.android.sdk.internal.TypesafeBackendImpl.getCurrentAddress(TypesafeBackendImpl.kt:169)
                 	at cash.z.ecc.android.sdk.internal.TypesafeBackendImpl$getCurrentAddress$1.invokeSuspend(Unknown Source:15)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:102)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
                 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c31982d, Dispatchers.Default]
                 Caused by: java.lang.RuntimeException: AccountUuid(cdd42738-3933-4e21-bfdd-39b076c041f3) is not known to the wallet
                 	at cash.z.ecc.android.sdk.internal.jni.RustBackend.getCurrentAddress(Native Method)
                 	at cash.z.ecc.android.sdk.internal.jni.RustBackend.access$getCurrentAddress(RustBackend.kt:27)
                 	at cash.z.ecc.android.sdk.internal.jni.RustBackend$Companion.getCurrentAddress(Unknown Source:0)
                 	at cash.z.ecc.android.sdk.internal.jni.RustBackend$Companion.access$getCurrentAddress(RustBackend.kt:499)
                 	at cash.z.ecc.android.sdk.internal.jni.RustBackend$getCurrentAddress$2.invokeSuspend(RustBackend.kt:149)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                 	at java.lang.Thread.run(Thread.java:1012)
```

- App Version: 
- Android Version:
- Device: (if applies)

**Comment by HonzaR** [comment]
I was able to reproduce this issue with this stacktrace:
```
DefaultDispatcher-worker-16    TypesafeBackendImpl.getCurrentAddress(): Currently unable to get current address
    java.lang.RuntimeException: Error while fetching address: no such table: addresses
    	at cash.z.ecc.android.sdk.internal.jni.RustBackend.getCurrentAddress(Native Method)
    	at cash.z.ecc.android.sdk.internal.jni.RustBackend.access$getCurrentAddress(RustBackend.kt:27)
    	at cash.z.ecc.android.sdk.internal.jni.RustBackend$Companion.getCurrentAddress(Unknown Source:0)
    	at cash.z.ecc.android.sdk.internal.jni.RustBackend$Companion.access$getCurrentAddress(RustBackend.kt:509)
    	at cash.z.ecc.android.sdk.internal.jni.RustBackend$getCurrentAddress$2.invokeSuspend(RustBackend.kt:159)
    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
    	at java.lang.Thread.run(Thread.java:1012)
 E  FATAL EXCEPTION: DefaultDispatcher-worker-6
    Process: co.electriccoin.zcash.debug, PID: 31640
    cash.z.ecc.android.sdk.exception.RustLayerException$GetCurrentAddressException: Error while requesting the current address from the Rust layer over JNI. This might mean that the SDK is not yet correctly set up.
    	at cash.z.ecc.android.sdk.internal.TypesafeBackendImpl.getCurrentAddress(TypesafeBackendImpl.kt:175)
    	at cash.z.ecc.android.sdk.internal.TypesafeBackendImpl$getCurrentAddress$1.invokeSuspend(Unknown Source:15)
    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:102)
    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@eae629e, Dispatchers.Default]
    Caused by: java.lang.RuntimeException: Error while fetching address: no such table: addresses
    	at cash.z.ecc.android.sdk.internal.jni.RustBackend.getCurrentAddress(Native Method)
    	at cash.z.ecc.android.sdk.internal.jni.RustBackend.access$getCurrentAddress(RustBackend.kt:27)
    	at cash.z.ecc.android.sdk.internal.jni.RustBackend$Companion.getCurrentAddress(Unknown Source:0)
    	at cash.z.ecc.android.sdk.internal.jni.RustBackend$Companion.access$getCurrentAddress(RustBackend.kt:509)
    	at cash.z.ecc.android.sdk.internal.jni.RustBackend$getCurrentAddress$2.invokeSuspend(RustBackend.kt:159)
    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
    	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by HonzaR** [comment]
Closing as resolved as part of the latest changes on the client side. Clients should wait for Synchronizer to set up before requesting accounts or addresses by checking its Status.
