### ISSUE TITLE
Caught exception while adding proofs to PCZT: RuntimeException: parameter file size is not correct

### ISSUE THREAD

**Issue by HonzaR** [Electric-Coin-Company/zcash-android-wallet-sdk#1662]
#### If so, please list the steps to reproduce below:
1. 
2. 
3. 

### Actual behavior + errors
```
co.electriccoin.zcash.debug DefaultDispatcher-worker-8     KeystoneProposalRepositoryImpl.invokeSuspend(): TEST KS2
2024-12-14 21:30:20.153 Twig                     E                              DefaultDispatcher-worker-8     TransactionEncoderImpl.addProofsToPczt(): Caught exception while adding proofs to PCZT.
                                                    java.lang.RuntimeException: parameter file size is not correct, please clean your Zcash parameters directory and re-run `fetch-params`.: Os { code: 2, kind: NotFound, message: "No such file or directory" }
                                                    	at cash.z.ecc.android.sdk.internal.jni.RustBackend.addProofsToPczt(Native Method)
                                                    	at cash.z.ecc.android.sdk.internal.jni.RustBackend.access$addProofsToPczt(RustBackend.kt:27)
                                                    	at cash.z.ecc.android.sdk.internal.jni.RustBackend$Companion.addProofsToPczt(Unknown Source:0)
                                                    	at cash.z.ecc.android.sdk.internal.jni.RustBackend$Companion.access$addProofsToPczt(RustBackend.kt:509)
                                                    	at cash.z.ecc.android.sdk.internal.jni.RustBackend.addProofsToPczt(RustBackend.kt:445)
                                                    	at cash.z.ecc.android.sdk.internal.TypesafeBackendImpl.addProofsToPczt(TypesafeBackendImpl.kt:157)
                                                    	at cash.z.ecc.android.sdk.internal.transaction.TransactionEncoderImpl.addProofsToPczt(TransactionEncoderImpl.kt:170)
                                                    	at cash.z.ecc.android.sdk.internal.transaction.OutboundTransactionManagerImpl.addProofsToPczt(OutboundTransactionManagerImpl.kt:113)
                                                    	at cash.z.ecc.android.sdk.SdkSynchronizer.addProofsToPczt(SdkSynchronizer.kt:867)
                                                    	at co.electriccoin.zcash.ui.common.repository.KeystoneProposalRepositoryImpl$createPCZTFromProposal$2.invokeSuspend(KeystoneProposalRepository.kt:205)
                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
```

- App Version: 
- Android Version:
- Device: (if applies)

**Comment by HonzaR** [comment]
Closing as resolved as part of the PCZT changes.
