### ISSUE TITLE
Resuming client app from background causes a crash in Synchronizer

### ISSUE THREAD

**Issue by nighthawk24** [Electric-Coin-Company/zcash-android-wallet-sdk#516]
Affects zcash-android-sdk:1.4.0-beta01

This is an issue affecting the Nighthawk Wallet when using the Zcash Android SDK

### Describe the issue
The Synchronizer does not seem to detect lifecycle of the app when the app is backgrounded, so when the user resumes the app, calls on the Synchronizer fail and the app crashes when resuming the app after a while. This could be a simple issue of setting the Synchronizer up with the lifecycle scope, it would be helpful if you could take a look at the logs and the link to the MainActivity where the Synchronizer is instantiated.

#### If so, please list the steps to reproduce below:
1. Open app, let sync finish
2. Background the app for 15+ minutes
3.  Resume the app

### Expected behaviour
Wallet app should resume and Synchronizer should reconnect without crashing the app.

### Actual behavior + errors
App Crash with the following logs:

 Process: com.nighthawkapps.wallet.android, PID: 22011
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nighthawkapps.wallet.android/com.nighthawkapps.wallet.android.ui.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property synchronizerComponent has not been initialized
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3707)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7870)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: kotlin.UninitializedPropertyAccessException: lateinit property synchronizerComponent has not been initialized
        at com.nighthawkapps.wallet.android.ui.MainActivity.getSynchronizerComponent(MainActivity.kt:90)
        at com.nighthawkapps.wallet.android.ui.home.HomeFragment$special$$inlined$viewModel$1.getValue(ViewModelExt.kt:63)
        at com.nighthawkapps.wallet.android.ui.home.HomeFragment$special$$inlined$viewModel$1.getValue(ViewModelExt.kt:8)
        at com.nighthawkapps.wallet.android.ui.home.HomeFragment.getViewModel(HomeFragment.kt:56)
        at com.nighthawkapps.wallet.android.ui.home.HomeFragment.onAttach(HomeFragment.kt:67)
        at androidx.fragment.app.Fragment.performAttach(Fragment.java:2954)
        at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:463)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:254)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1374)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2841)
        at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2773)
        at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1935)
        at androidx.fragment.app.Fragment.onCreate(Fragment.java:1911)
        at androidx.navigation.fragment.NavHostFragment.onCreate(NavHostFragment.kt:169)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2981)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:474)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1374)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2841)
        at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2773)
        at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:251)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:252)
        at com.nighthawkapps.wallet.android.ui.MainActivity.onCreate(MainActivity.kt:126)
        at android.app.Activity.performCreate(Activity.java:8054)
        at android.app.Activity.performCreate(Activity.java:8034)

- App Version: 
- Android Version:  https://github.com/nighthawk-apps/nighthawk-wallet-android/blob/fd57c42a820793b086a0181e34973ad1d53675b4/app/src/main/java/com/nighthawkapps/wallet/android/ui/MainActivity.kt#L90
- Device: (if applies) Pixel 3a

**Comment by ccjernigan** [comment]
By design, the SDK and Synchronizer are not lifecycle aware, since they can be used outside of the UI in some use cases.  Why do you believe this is a bug in the SDK?

This appears to be a bug in the UI.  The stacktrace seems to point to the issue—the `lateinit var synchronizerComponent` is null.  Although I haven't traced the code very closely, the fact that `synchronizerComponent` is initialized lazily indicates there's probably a timing issue in the UI when the app is relaunched.

Given the steps to reproduce (wait 15 minutes) it seems like it might be due to state restoration.  Check what Android version you're using and whether you're pressing Home or Back to exit the app, as that could help you track down the bug further.  My suspicion is that reproduction requires the app being killed, then going through state restoration with an onSavedInstanceState bundle present.
